build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
install:
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install -e ."
  # Install ffmpeg
  - ps: Start-FileDownload ('http://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-latest-win64-shared.7z') ffmpeg-shared.7z
  - 7z x ffmpeg-shared.7z > NULL
  - "SET PATH=%cd%\\ffmpeg-latest-win64-shared\\bin;%PATH%"
test_script:
  - "%PYTHON%/python.exe test/test.py"
